// <auto-generated />
using EarthlyRemedies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EarthlyRemedies.Migrations
{
    [DbContext(typeof(EarthlyRemediesContext))]
    [Migration("20200610174331_AddJoinCategoryRemedy")]
    partial class AddJoinCategoryRemedy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EarthlyRemedies.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "GI"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Respiratory"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Skin"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Eyes"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Hair"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Musculoskeletal"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Endocrine"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Chakra"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Pineal"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Lymphatic"
                        },
                        new
                        {
                            CategoryId = 11,
                            Name = "Cardiovascular"
                        },
                        new
                        {
                            CategoryId = 12,
                            Name = "Digestive"
                        },
                        new
                        {
                            CategoryId = 13,
                            Name = "Nerve"
                        },
                        new
                        {
                            CategoryId = 14,
                            Name = "Reproductive"
                        });
                });

            modelBuilder.Entity("EarthlyRemedies.Models.CategoryRemedy", b =>
                {
                    b.Property<int>("CategoryRemedyId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<int>("RemedyId");

                    b.HasKey("CategoryRemedyId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RemedyId");

                    b.ToTable("CategoryRemedy");

                    b.HasData(
                        new
                        {
                            CategoryRemedyId = 1,
                            CategoryId = 2,
                            RemedyId = 1
                        },
                        new
                        {
                            CategoryRemedyId = 2,
                            CategoryId = 5,
                            RemedyId = 2
                        },
                        new
                        {
                            CategoryRemedyId = 3,
                            CategoryId = 6,
                            RemedyId = 3
                        },
                        new
                        {
                            CategoryRemedyId = 4,
                            CategoryId = 4,
                            RemedyId = 4
                        },
                        new
                        {
                            CategoryRemedyId = 5,
                            CategoryId = 3,
                            RemedyId = 5
                        },
                        new
                        {
                            CategoryRemedyId = 6,
                            CategoryId = 12,
                            RemedyId = 6
                        },
                        new
                        {
                            CategoryRemedyId = 7,
                            CategoryId = 3,
                            RemedyId = 7
                        },
                        new
                        {
                            CategoryRemedyId = 8,
                            CategoryId = 12,
                            RemedyId = 8
                        },
                        new
                        {
                            CategoryRemedyId = 9,
                            CategoryId = 2,
                            RemedyId = 9
                        },
                        new
                        {
                            CategoryRemedyId = 10,
                            CategoryId = 4,
                            RemedyId = 10
                        });
                });

            modelBuilder.Entity("EarthlyRemedies.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<int>("RemedyId");

                    b.Property<int>("Stars");

                    b.Property<int>("UserId");

                    b.HasKey("RatingId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            Comments = "Almost killed me!",
                            RemedyId = 2,
                            Stars = 1,
                            UserId = 2
                        },
                        new
                        {
                            RatingId = 2,
                            Comments = "Not sure it did anything.",
                            RemedyId = 2,
                            Stars = 3,
                            UserId = 1
                        },
                        new
                        {
                            RatingId = 3,
                            Comments = "Best ever!!!",
                            RemedyId = 2,
                            Stars = 5,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("EarthlyRemedies.Models.Remedy", b =>
                {
                    b.Property<int>("RemedyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ailment")
                        .HasMaxLength(30);

                    b.Property<string>("Details")
                        .IsRequired();

                    b.Property<string>("Ingredients");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("UserId");

                    b.HasKey("RemedyId");

                    b.ToTable("Remedies");

                    b.HasData(
                        new
                        {
                            RemedyId = 1,
                            Ailment = "chest congestion",
                            Details = "L-Acetyl Cysteine, taken daily, will shorten duration of respiratory ailments.",
                            Ingredients = "L-Acetyl Cysteine",
                            Name = "Mucus Melter",
                            UserId = 1
                        },
                        new
                        {
                            RemedyId = 2,
                            Ailment = "dandruff",
                            Details = "Castor oil rubbed into the scalp, every night before bed, for one week.",
                            Ingredients = "castor oil",
                            Name = "Dandruff Buster",
                            UserId = 2
                        },
                        new
                        {
                            RemedyId = 3,
                            Ailment = "muscle soreness",
                            Details = "Mix 2 drops eucalyptus oil, 1 drop peppermint oil, and 1 drop tea tree oil into 1 oz neutral oil or balm.  Rub on sore muscles before sleep.",
                            Ingredients = "tea tree oil, peppermint, eucalyptus",
                            Name = "Sore Muscle Balm",
                            UserId = 2
                        },
                        new
                        {
                            RemedyId = 4,
                            Ailment = "dry eyes",
                            Details = "Mega doses of Omega 3s for LIFE!!!!",
                            Ingredients = "Omega 3",
                            Name = "Dry Eye Relief",
                            UserId = 1
                        },
                        new
                        {
                            RemedyId = 5,
                            Ailment = "foot fungus",
                            Details = "Soak the affected area in apple cider vinegar twice a day until cured",
                            Ingredients = "apple cider vinegar",
                            Name = "Fungus Foiler",
                            UserId = 2
                        },
                        new
                        {
                            RemedyId = 6,
                            Ailment = "digestive illness",
                            Details = "One shot of vodka, followed by one shot of fresh ginger juice, daily until symptoms resolve.",
                            Ingredients = "ginger, vodka",
                            Name = "Polish Tummy Cure",
                            UserId = 1
                        },
                        new
                        {
                            RemedyId = 7,
                            Ailment = "sunburn",
                            Details = "apply earl grey tea to the affected area 5 times a day until burn goes away",
                            Ingredients = "tea",
                            Name = "Sunburn salve",
                            UserId = 2
                        },
                        new
                        {
                            RemedyId = 8,
                            Ailment = "heartburn",
                            Details = "Heat 4 oz water to body temperature.  Add 1 oz fresh lemon juice. Drink slowly.",
                            Ingredients = "lemon",
                            Name = "Heartburn Helper",
                            UserId = 1
                        },
                        new
                        {
                            RemedyId = 9,
                            Ailment = "cough",
                            Details = "Mix 2 drops eucalyptus oil, 1 drop peppermint oil, and 1 drop tea tree oil into 1 oz neutral oil or balm.  Rub on throat, chest and upper back before sleep.",
                            Ingredients = "tea tree oil, peppermint, eucalyptus",
                            Name = "Nighttime Salve",
                            UserId = 2
                        },
                        new
                        {
                            RemedyId = 10,
                            Ailment = "eye obstruction",
                            Details = "If something is in your eye, pull your upper eyelid over your lower one, in an attempt to scrape out the obstruction",
                            Ingredients = "",
                            Name = "Eye obsruction removal",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("EarthlyRemedies.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ethan",
                            LastName = "Firpo",
                            Password = "epicodusRocks",
                            Username = "efirpo"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Tyler",
                            LastName = "Bates",
                            Password = "x",
                            Username = "tyty"
                        });
                });

            modelBuilder.Entity("EarthlyRemedies.Models.CategoryRemedy", b =>
                {
                    b.HasOne("EarthlyRemedies.Models.Category", "Category")
                        .WithMany("Remedies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EarthlyRemedies.Models.Remedy", "Remedy")
                        .WithMany("Categories")
                        .HasForeignKey("RemedyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
