// <auto-generated />
using EarthlyRemedies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EarthlyRemedies.Migrations
{
    [DbContext(typeof(EarthlyRemediesContext))]
    partial class EarthlyRemediesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EarthlyRemedies.Models.Remedy", b =>
                {
                    b.Property<int>("RemedyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ailment");

                    b.Property<string>("Details");

                    b.Property<string>("Name");

                    b.HasKey("RemedyId");

                    b.ToTable("Remedies");
                });
#pragma warning restore 612, 618
        }
    }
}
